GET http://localhost:8082/products
Accept: text/html

###

GET http://localhost:8082/products?search=Apfel&cheaperThan=4
Accept: text/html

###

GET http://localhost:8082/products?search=Apfel
Accept: text/html

###

GET http://localhost:8082/products?cheaperThan=4
Accept: text/html

###
