GET http://localhost:8081/products
Accept: text/html

###

GET http://localhost:8081/products?search=Apfel&cheaperThan=4
Accept: text/html

###

GET http://localhost:8081/products?search=Apfel
Accept: text/html

###

GET http://localhost:8081/products?cheaperThan=4
Accept: text/html

###
