POST http://localhost:8081/products
Content-Type: application/de.dhbw.product+json
Accept: application/de.dhbw.product+json

{
  "name": "Banane",
  "price": 3
}

###

POST http://localhost:8081/products
Content-Type: application/de.dhbw.product+json
Accept: application/de.dhbw.product+json

{
  "name": "Apfel",
  "price": 7
}

###

POST http://localhost:8081/products
Content-Type: application/de.dhbw.product+json
Accept: application/de.dhbw.product+json

{
  "name": "",
  "price": 0
}

###
